template_path: templates/dependencies/dependent_template_local_export.json
region: eu-west-1
parameters:
  DependentStackName: !stack_output_external sceptre-integration-tests-62c92a0c998111e8a0cad600a930ca01-9-A::StackName 9-A
